// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MassTransit.RedisSagas")]
[assembly: AssemblyDescriptionAttribute("MassTransit.RedisSagas is a distributed application framework for .NET https://github.com/Royal-Jay/MassTransit.RedisSagas")]
[assembly: AssemblyProductAttribute("MassTransit.RedisSagas")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.0 (testWork/7f42995e)")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "MassTransit.RedisSagas";
        internal const System.String AssemblyDescription = "MassTransit.RedisSagas is a distributed application framework for .NET https://github.com/Royal-Jay/MassTransit.RedisSagas";
        internal const System.String AssemblyProduct = "MassTransit.RedisSagas";
        internal const System.String AssemblyVersion = "1.0.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0.0";
        internal const System.String AssemblyInformationalVersion = "1.0.0.0 (testWork/7f42995e)";
    }
}
